version: "3"

services:
  pet-service:
    build: .
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    external: true
